// Shared template definitions used by:
//  - TemplatesGallery (phone mockup preview)
//  - Public profile page (ProfileHeader + LinkCard colors)
//  - Dashboard ProfileSection (template switcher)

export const templates = [
  {
    id: 1,
    name: "Dark Mode",
    category: "Dark",
    // Phone mockup fields
    phoneBg: "#0f172a", screenBg: "#1e293b", statusBg: "#0f172a", avatarText: "DM",
    links: ["Portfolio", "YouTube", "Newsletter"],
    // Public profile fields
    panelDark: true,
    panelBg: "#0f172a",
    accentColor: "#6366f1",
    avatarTextColor: "#ffffff",
    nameColor: "#e2e8f0",
    handleColor: "#94a3b8",
    linkBg: "#334155",
    linkColor: "#e2e8f0",
  },
  {
    id: 2,
    name: "Minimal",
    category: "Light",
    phoneBg: "#e8e8e6", screenBg: "#ffffff", statusBg: "#f3f3f1", avatarText: "MI",
    links: ["Blog", "Shop", "Contact"],
    panelDark: false,
    panelBg: "#ffffff",
    accentColor: "#1a1a1a",
    avatarTextColor: "#ffffff",
    nameColor: "#1a1a1a",
    handleColor: "#6b6b6b",
    linkBg: "#f3f3f1",
    linkColor: "#1a1a1a",
  },
  {
    id: 3,
    name: "Purple Haze",
    category: "Dark",
    phoneBg: "#2e1065", screenBg: "#502274", statusBg: "#3b0764", avatarText: "PH",
    links: ["Music", "Tour Dates", "Merch"],
    panelDark: true,
    panelBg: "#2e1065",
    accentColor: "#d2e823",
    avatarTextColor: "#2e1065",
    nameColor: "#ffffff",
    handleColor: "#c4b5fd",
    linkBg: "#ffffff",
    linkColor: "#502274",
  },
  {
    id: 4,
    name: "Sunset",
    category: "Colorful",
    phoneBg: "#7c2d12", screenBg: "#fed7aa", statusBg: "#9a3412", avatarText: "SS",
    links: ["Recipes", "Instagram", "Cookbook"],
    panelDark: true,
    panelBg: "#7c2d12",
    accentColor: "#f97316",
    avatarTextColor: "#7c2d12",
    nameColor: "#fed7aa",
    handleColor: "#fdba74",
    linkBg: "#fed7aa",
    linkColor: "#7c2d12",
  },
  {
    id: 5,
    name: "Forest",
    category: "Dark",
    phoneBg: "#052e16", screenBg: "#14532d", statusBg: "#052e16", avatarText: "FO",
    links: ["Wellness", "Classes", "Shop"],
    panelDark: true,
    panelBg: "#052e16",
    accentColor: "#d2e823",
    avatarTextColor: "#052e16",
    nameColor: "#dcfce7",
    handleColor: "#86efac",
    linkBg: "#dcfce7",
    linkColor: "#14532d",
  },
  {
    id: 6,
    name: "Ocean",
    category: "Dark",
    phoneBg: "#0c4a6e", screenBg: "#0369a1", statusBg: "#0c4a6e", avatarText: "OC",
    links: ["Portfolio", "GitHub", "Blog"],
    panelDark: true,
    panelBg: "#0c4a6e",
    accentColor: "#38bdf8",
    avatarTextColor: "#0c4a6e",
    nameColor: "#e0f2fe",
    handleColor: "#7dd3fc",
    linkBg: "#e0f2fe",
    linkColor: "#0c4a6e",
  },
  {
    id: 7,
    name: "Blossom",
    category: "Light",
    phoneBg: "#fdf2f8", screenBg: "#fce7f3", statusBg: "#fbcfe8", avatarText: "BL",
    links: ["Fashion", "Collabs", "Press"],
    panelDark: false,
    panelBg: "#fdf2f8",
    accentColor: "#ec4899",
    avatarTextColor: "#ffffff",
    nameColor: "#831843",
    handleColor: "#9d174d",
    linkBg: "#831843",
    linkColor: "#fce7f3",
  },
  {
    id: 8,
    name: "Neon",
    category: "Colorful",
    phoneBg: "#09090b", screenBg: "#18181b", statusBg: "#09090b", avatarText: "NE",
    links: ["Music", "Events", "Store"],
    panelDark: true,
    panelBg: "#09090b",
    accentColor: "#a3e635",
    avatarTextColor: "#09090b",
    nameColor: "#a3e635",
    handleColor: "#4ade80",
    linkBg: "#a3e635",
    linkColor: "#09090b",
  },
];

// Returns the template object by ID, defaults to template 1
export const getTemplate = (id) => templates.find((t) => t.id === Number(id)) ?? templates[0];
